site_name: Curve Resources Russia
site_url: https://resources.curve.fi/ru/
site_author: CurveFi
docs_dir: '../../docs/ru'                           # Where to find the English markdown files
site_dir: '../../generated/ru'  

plugins:
  - search
  - autolinks
  - typeset
  - minify:
      minify_html: true


# extension
markdown_extensions:
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  custom_dir: ../../overrides
  include_search_page: false
  search_index_only: true
  font:
    text: Roboto
    code: Roboto Mono
  logo: "images/lama.png"
  favicon: "images/lama.png"
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.tabs.link
    - content.footnote.tooltips
    - navigation.indexes
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy

  palette:
    # - media: "(prefers-color-scheme: dark)"
    - scheme: default
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # - media: "(prefers-color-scheme: light)"
    - scheme: slate
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: русский
      link: /ru/
      lang: ru
  generator: false
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/curvefi
      name: Telegram
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/curvefinance
      name: X
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rgrfS7W
      name: Discord
    - icon: fontawesome/brands/youtube
      link: http://www.youtube.com/c/CurveFinance
      name: YouTube

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_name: CurveDocs/curve-resources
repo_url: https://github.com/CurveDocs/curve-resources


nav:
  - Home: index.md
  - Links:
    - Curve.fi: https://curve.fi/#/ethereum/swap
    - Curve DAO: https://dao.curve.fi/
    - Curve News: https://news.curve.fi/
    - Discord: https://discord.gg/twUngQYz85
    - Github: https://github.com/curvefi/
    - Governance Forum: https://gov.curve.fi/
    - Twitter: https://twitter.com/curvefinance
    - Technical Docs: https://docs.curve.fi/
    - Telegram: https://t.me/curvefi
